//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certamen_3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACREDITACION
    {
        public int ID_ACREDITACION { get; set; }
        public int ID_TIPO_ACREDITACION { get; set; }
        public string DV_CLIENTE { get; set; }
        public int RUT_CLIENTE { get; set; }
        public string NOM_USUARIO { get; set; }
        public System.DateTime FECHA_CREADO { get; set; }
        public System.DateTime FECHA_CONTABLE { get; set; }
        public int TOTAL_N_CUOTAS { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_ACREDITACION TIPO_ACREDITACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
