//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certamen_3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ACREDITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ACREDITACION()
        {
            this.ACREDITACIONs = new HashSet<ACREDITACION>();
        }
    
        public int ID_TIPO_ACREDITACION { get; set; }
        public string DESC_TIPO_ACREDITACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACREDITACION> ACREDITACIONs { get; set; }
    }
}
