//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certamen_3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ACREDITACIONs = new HashSet<ACREDITACION>();
        }
    
        public string NOM_USUARIO { get; set; }
        public string NOMBRES_USUARIO { get; set; }
        public string APELLIDOS_USUARIO { get; set; }
        public string CONTRASEÑA_USUARIO { get; set; }
        public int ID_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACREDITACION> ACREDITACIONs { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
